In [1]:
# Import Dependencies
import pandas as pd

In [2]:
# Create reference to CSV file
csv_path = "Resources/Soccer2018Data.csv"

# Import the CSV into a pandas DataFrame
soccer_2018_df = pd.read_csv(csv_path, low_memory=False)
soccer_2018_df

,Name,Age,Nationality,Overall,Potential,Club,Preferred Position,CAM,CB,CDM,...,RB,RCB,RCM,RDM,RF,RM,RS,RW,RWB,ST
0,Cristiano Ronaldo,32,Portugal,94,94,Real Madrid CF,ST,89.0,53.0,62.0,...,61.0,53.0,82.0,62.0,91.0,89.0,92.0,91.0,66.0,92.0
1,L. Messi,30,Argentina,93,93,FC Barcelona,RW,92.0,45.0,59.0,...,57.0,45.0,84.0,59.0,92.0,90.0,88.0,91.0,62.0,88.0
2,Neymar,25,Brazil,92,94,Paris Saint-Germain,LW,88.0,46.0,59.0,...,59.0,46.0,79.0,59.0,88.0,87.0,84.0,89.0,64.0,84.0
3,L. Suárez,30,Uruguay,92,92,FC Barcelona,ST,87.0,58.0,65.0,...,64.0,58.0,80.0,65.0,88.0,85.0,88.0,87.0,68.0,88.0
4,M. Neuer,31,Germany,92,92,FC Bayern Munich,GK,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17976,A. Kelsey,17,England,46,63,Scunthorpe United,GK,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17977,B. Richardson,47,England,46,46,Wycombe Wanderers,GK,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17978,J. Young,17,Scotland,46,61,Swindon Town,ST,44.0,28.0,29.0,...,31.0,28.0,38.0,29.0,45.0,42.0,45.0,44.0,32.0,45.0
17979,J. Lundstram,18,England,46,64,Crewe Alexandra,CM,45.0,46.0,47.0,...,47.0,46.0,45.0,47.0,43.0,45.0,41.0,44.0,46.0,41.0
17980,L. Sackey,18,Ghana,46,64,Scunthorpe United,ST,29.0,45.0,38.0,...,40.0,45.0,30.0,38.0,29.0,30.0,31.0,29.0,38.0,31.0

In [ ]:
# Collect a list of all the unique values in "Preferred Position"
soccer_2018_df.unique()

In [ ]:
# Looking only at strikers (ST) to start

In [ ]:
# Sort the DataFrame by the values in the "ST" column to find the worst

# Reset the index so that the index is now based on the sorting locations

In [ ]:
# Save all of the information collected on the worst striker